"""
Schemas for Large Language Model (LLM) providers.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class LLMMessage(BaseModel):
    """
    Represents a single message sent to the LLM.
    """

    role: str = Field(
        ...,
        description="Message role such as system, user, or assistant.",
    )

    content: str = Field(
        ...,
        min_length=1,
        description="Message content.",
    )

    model_config = ConfigDict(frozen=True)


class LLMRequest(BaseModel):
    """
    Represents a request sent to an LLM provider.
    """

    messages: list[LLMMessage] = Field(
        ...,
        min_length=1,
        description="Conversation messages sent to the LLM.",
    )

    temperature: float = Field(
        default=0.7,
        ge=0.0,
        description="Controls randomness of the generated response.",
    )

    max_tokens: int | None = Field(
        default=None,
        gt=0,
        description="Maximum number of tokens to generate.",
    )

    model_config = ConfigDict(frozen=True)


class LLMResponse(BaseModel):
    """
    Represents the response generated by an LLM provider.
    """

    content: str = Field(
        ...,
        min_length=1,
        description="Generated response text.",
    )

    model: str | None = Field(
        default=None,
        description="Model used to generate the response.",
    )

    finish_reason: str | None = Field(
        default=None,
        description="Reason why generation stopped.",
    )

    usage: dict[str, int] | None = Field(
        default=None,
        description="Token usage information.",
    )

    model_config = ConfigDict(frozen=True)