"""
LLM service.

Provides a high-level interface for generating responses
without exposing provider-specific implementation details.
"""

from __future__ import annotations

from app.ai.llm.base import BaseLLM
from app.ai.llm.factory import create_llm
from app.ai.llm.schemas import LLMMessage, LLMRequest, LLMResponse
from app.core.logging import get_logger


logger = get_logger(__name__)


class LLMService:
    """
    High-level service responsible for LLM generation.

    The service sits between the conversation layer and
    the configured LLM provider.
    """

    def __init__(
        self,
        llm: BaseLLM | None = None,
    ) -> None:
        self._llm = (
            llm
            if llm is not None
            else create_llm()
        )

    async def generate(
        self,
        user_text: str,
    ) -> LLMResponse:
        """
        Generate an LLM response for user input.

        Args:
            user_text: User's message.

        Returns:
            LLMResponse generated by the configured provider.
        """

        logger.info(
            "Generating response through LLM service: %r",
            user_text,
        )

        request = LLMRequest(
            messages=[
                LLMMessage(
                    role="user",
                    content=user_text,
                )
            ],
        )

        response = await self._llm.generate(request)

        logger.info(
            "LLM service generated response: %r",
            response.content,
        )

        return response