"""
Pipecat frames for conversation-layer communication.
"""

from __future__ import annotations

from dataclasses import dataclass

from pipecat.frames.frames import Frame


@dataclass
class ConversationResponseFrame(Frame):
    """
    Carries a response generated by the conversation engine.

    This is the Pipecat-layer representation of a
    ConversationOutput.
    """

    text: str